name: GitHub Contribution

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub contribution svg
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 1000
          SETTING_JSON: "contribution/settings.json"
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Update contribution svg"
          git push
